"""MQ-8 canonical v1 achievement content. Definition metadata only."""
from __future__ import annotations

from .models import AchievementDefinition, Category, EvidenceLevel, StackPolicy
from .registry import build_registry

STATUS_BY_ID = {
    'ACH-001': 'HISTORICAL_REPLAY_ELIGIBLE',
    'ACH-002': 'HISTORICAL_REPLAY_ELIGIBLE',
    'ACH-003': 'HISTORICAL_REPLAY_ELIGIBLE',
    'ACH-004': 'HISTORICAL_REPLAY_ELIGIBLE',
    'ACH-005': 'HISTORICAL_REPLAY_ELIGIBLE',
    'ACH-006': 'HISTORICAL_REPLAY_ELIGIBLE',
    'ACH-007': 'HISTORICAL_REPLAY_ELIGIBLE',
    'ACH-008': 'HISTORICAL_REPLAY_ELIGIBLE',
    'ACH-009': 'HISTORICAL_REPLAY_ELIGIBLE',
    'ACH-010': 'HISTORICAL_CANDIDATE',
    'ACH-011': 'DEFERRED',
    'ACH-012': 'DEFERRED',
    'ACH-013': 'DEFERRED',
    'ACH-014': 'DEFERRED',
    'ACH-015': 'DEFERRED',
    'ACH-016': 'DEFERRED',
    'ACH-017': 'DEFERRED',
    'ACH-018': 'DEFERRED',
    'ACH-019': 'HISTORICAL_REPLAY_ELIGIBLE',
    'ACH-020': 'HISTORICAL_REPLAY_ELIGIBLE',
    'ACH-033': 'HISTORICAL_CANDIDATE',
    'ACH-034': 'HISTORICAL_CANDIDATE',
    'ACH-035': 'DEFERRED',
    'ACH-036': 'HISTORICAL_CANDIDATE',
    'ACH-037': 'DEFERRED',
    'ACH-038': 'DEFERRED',
    'ACH-039': 'DEFERRED',
    'ACH-040': 'DEFERRED',
    'ACH-041': 'DEFERRED',
    'ACH-042': 'DEFERRED',
    'ACH-049': 'DEFERRED',
    'ACH-050': 'DEFERRED',
    'ACH-051': 'DEFERRED',
    'ACH-052': 'DEFERRED',
    'ACH-053': 'DEFERRED',
    'ACH-054': 'DEFERRED',
    'ACH-055': 'DEFERRED',
    'ACH-056': 'DEFERRED',
    'ACH-065': 'DEFERRED',
    'ACH-066': 'DEFERRED',
    'ACH-067': 'DEFERRED',
    'ACH-068': 'DEFERRED',
    'ACH-069': 'DEFERRED',
    'ACH-070': 'DEFERRED',
    'ACH-071': 'DEFERRED',
    'ACH-072': 'DEFERRED',
    'ACH-073': 'DEFERRED',
    'ACH-074': 'DEFERRED',
    'ACH-089': 'DEFERRED',
    'ACH-090': 'MANUAL_CANON',
    'ACH-091': 'DEFERRED',
    'ACH-092': 'DEFERRED',
    'ACH-093': 'DEFERRED',
    'ACH-094': 'DEFERRED',
    'ACH-095': 'DEFERRED',
    'ACH-096': 'MANUAL_CANON',
    'ACH-113': 'DEFERRED',
    'ACH-114': 'DEFERRED',
    'ACH-121': 'MANUAL_CANON',
    'ACH-128': 'PERMANENTLY_LOCKED',
    'ACH-129': 'DEFERRED',
    'ACH-130': 'DEFERRED',
    'ACH-131': 'DEFERRED',
    'ACH-132': 'DEFERRED',
    'ACH-133': 'DEFERRED',
    'ACH-134': 'DEFERRED',
    'ACH-135': 'DEFERRED',
    'ACH-136': 'DEFERRED',
    'ACH-137': 'DEFERRED',
    'ACH-138': 'DEFERRED',
    'ACH-139': 'MANUAL_CANON',
    'ACH-140': 'DEFERRED',
    'ACH-141': 'DEFERRED',
    'ACH-142': 'DEFERRED',
    'ACH-143': 'DEFERRED',
    'ACH-144': 'DEFERRED',
    'ACH-145': 'DEFERRED',
    'ACH-146': 'DEFERRED',
    'ACH-147': 'DEFERRED',
    'ACH-148': 'DEFERRED',
    'ACH-149': 'DEFERRED',
    'ACH-150': 'DEFERRED',
    'ACH-151': 'DEFERRED',
    'ACH-152': 'DEFERRED',
    'ACH-021': 'DEFERRED',
    'ACH-057': 'DEFERRED',
    'ACH-097': 'DEFERRED',
}

V1_DEFINITIONS = (
    AchievementDefinition(
        achievement_id='ACH-001',
        version="1.0",
        trigger_version="historical-evidence/v1",
        title='MISSION FAILED SUCCESSFULLY',
        category=Category.SCIENCE,
        evidence_level=EvidenceLevel.E2,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Hypothesis dead. Science alive.',
        science_text='A preregistered null constrains the next question.',
        evidence_refs=('docs/experiments/mq7-14-residual-branch-mediation-protocol.md',),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-002',
        version="1.0",
        trigger_version="historical-evidence/v1",
        title='THE WIRE WAS HAUNTED',
        category=Category.SCIENCE,
        evidence_level=EvidenceLevel.E3,
        stack_policy=StackPolicy.SINGLE,
        public_text='We removed the haunted wire.',
        science_text='Validated-edge ablation removes the measured effect while the matched control lesion does not.',
        evidence_refs=('docs/experiments/mq7-11-causal-route-ablation-protocol.md',),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-003',
        version="1.0",
        trigger_version="historical-evidence/v1",
        title='ROUTING TABLES',
        category=Category.SCIENCE,
        evidence_level=EvidenceLevel.E3,
        stack_policy=StackPolicy.SINGLE,
        public_text='The ghost had routing tables.',
        science_text='Cumulative first-wave mediation explains at least 95% of the measured downstream effect.',
        evidence_refs=('docs/experiments/mq7-17-cumulative-first-wave-mediation-results.md',),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-004',
        version="1.0",
        trigger_version="historical-evidence/v1",
        title='TEN BUTTONS',
        category=Category.SCIENCE,
        evidence_level=EvidenceLevel.E2,
        stack_policy=StackPolicy.SINGLE,
        public_text='GLaDOS found ten buttons.',
        science_text='Ten frozen SC-01 targets expose the latent SC-03 state.',
        evidence_refs=('docs/experiments/mq7-9-shock-target-specificity-protocol.md',),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-005',
        version="1.0",
        trigger_version="historical-evidence/v1",
        title='LOOKING BUSY',
        category=Category.SCIENCE,
        evidence_level=EvidenceLevel.E3,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Outstanding activity. Zero contribution.',
        science_text='Large early differential signal coexists with zero measured lesion attenuation.',
        evidence_refs=('docs/experiments/mq7-16-first-wave-causal-screen-protocol.md',),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-006',
        version="1.0",
        trigger_version="historical-evidence/v1",
        title='SPAGHETTI CONNECTOME',
        category=Category.SCIENCE,
        evidence_level=EvidenceLevel.E3,
        stack_policy=StackPolicy.SINGLE,
        public_text='The wiring diagram was more of a suggestion.',
        science_text='Static structural ranking fails while dynamic tracing identifies useful causal candidates.',
        evidence_refs=('docs/experiments/mq7-13-residual-route-discovery-protocol.md',),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-007',
        version="1.0",
        trigger_version="historical-evidence/v1",
        title='BOOMERANG NEURON',
        category=Category.SCIENCE,
        evidence_level=EvidenceLevel.E2,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='The signal came back.',
        science_text='Divergence later returns to the original perturbation node in the frozen trace.',
        evidence_refs=('docs/experiments/mq7-15-differential-trace-protocol.md',),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-008',
        version="1.0",
        trigger_version="historical-evidence/v1",
        title='STEALTH BUILD',
        category=Category.SCIENCE,
        evidence_level=EvidenceLevel.E3,
        stack_policy=StackPolicy.SINGLE,
        public_text='Passive effect: hidden.',
        science_text='Persistent plasticity is silent at baseline and measurable under matched perturbation.',
        evidence_refs=('docs/experiments/mq7-8-shock-plasticity-interaction-results.md',),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-009',
        version="1.0",
        trigger_version="historical-evidence/v1",
        title='CRITICAL HIT',
        category=Category.SCIENCE,
        evidence_level=EvidenceLevel.E2,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='That one reached the decision layer.',
        science_text='An acute intervention changes the anonymous final decision in the frozen replay.',
        evidence_refs=('docs/experiments/mq7-8-shock-plasticity-interaction-results.md',),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-010',
        version="1.0",
        trigger_version="historical-evidence/v1",
        title='STILL ALIVE, SOMEHOW',
        category=Category.SCIENCE,
        evidence_level=EvidenceLevel.E2,
        stack_policy=StackPolicy.SINGLE,
        public_text='Structural integrity: annoyingly intact.',
        science_text='Integrated intervention execution preserves the frozen structural connectome.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-011',
        version="1.0",
        trigger_version="historical-evidence/v1",
        title='NEW GAME PLUS',
        category=Category.SCIENCE,
        evidence_level=EvidenceLevel.E4,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Same fly. New seed. Same problem.',
        science_text='An accepted effect class reproduces under an independently frozen seed or runtime.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-012',
        version="1.0",
        trigger_version="historical-evidence/v1",
        title='THE CONTROL WAS THE CONTENT',
        category=Category.SCIENCE,
        evidence_level=EvidenceLevel.E3,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Plot twist: the boring run mattered.',
        science_text='A preregistered control materially constrains causal interpretation.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-013',
        version="1.0",
        trigger_version="historical-evidence/v1",
        title='NO REROLLS',
        category=Category.SCIENCE,
        evidence_level=EvidenceLevel.E2,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='RNG has spoken.',
        science_text='A frozen deterministic selection is retained despite an inconvenient or null outcome.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-014',
        version="1.0",
        trigger_version="historical-evidence/v1",
        title='BRAINROT PASSED PEER REVIEW',
        category=Category.SCIENCE,
        evidence_level=EvidenceLevel.E3,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Unfortunately, the data agree.',
        science_text='A narratively absurd result survives the frozen control structure.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-015',
        version="1.0",
        trigger_version="historical-evidence/v1",
        title='THERE ARE FOUR LIGHTS',
        category=Category.SCIENCE,
        evidence_level=EvidenceLevel.E3,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='The measurement remains the measurement.',
        science_text='Repeated measurements remain consistent despite pressure to reinterpret the observation.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-016',
        version="1.0",
        trigger_version="historical-evidence/v1",
        title='THE PRIME DIRECTIVE',
        category=Category.SCIENCE,
        evidence_level=EvidenceLevel.E2,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Interference denied.',
        science_text='A post-hoc change is rejected because it would contaminate the frozen protocol.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-017',
        version="1.0",
        trigger_version="historical-evidence/v1",
        title='Q DID IT',
        category=Category.SCIENCE,
        evidence_level=EvidenceLevel.E2,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Explanation pending. Mischief suspected.',
        science_text='A reproducible anomaly remains unexplained under the current model.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-018',
        version="1.0",
        trigger_version="historical-evidence/v1",
        title='DATA WOULD LIKE A WORD',
        category=Category.SCIENCE,
        evidence_level=EvidenceLevel.E2,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Please consult the actual data.',
        science_text='Narrative wording is corrected back to the supported telemetry claim.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-019',
        version="1.0",
        trigger_version="historical-evidence/v1",
        title='DIMENSIONAL MERGE',
        category=Category.SCIENCE,
        evidence_level=EvidenceLevel.E3,
        stack_policy=StackPolicy.SINGLE,
        public_text='Two states entered. One interaction left.',
        science_text='A latent persistent state becomes measurable only under a second matched perturbation.',
        evidence_refs=('docs/experiments/mq7-8-shock-plasticity-interaction-results.md',),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-020',
        version="1.0",
        trigger_version="historical-evidence/v1",
        title='99.9999%',
        category=Category.SCIENCE,
        evidence_level=EvidenceLevel.E3,
        stack_policy=StackPolicy.SINGLE,
        public_text='Close enough for government neuroscience.',
        science_text='Cumulative tested branches reduce the residual measured effect below 0.001% of intact magnitude.',
        evidence_refs=('docs/experiments/mq7-17-cumulative-first-wave-mediation-results.md',),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-033',
        version="1.0",
        trigger_version="historical-evidence/v1",
        title='THE CAKE WAS NEVER BUDGETED',
        category=Category.ORACLE,
        evidence_level=EvidenceLevel.E2,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='MERCY executed successfully. Nothing happened.',
        science_text='SC-06 MERCY executes correctly and produces a valid null effect.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-034',
        version="1.0",
        trigger_version="historical-evidence/v1",
        title='STATUS EFFECT: SCARRED',
        category=Category.ORACLE,
        evidence_level=EvidenceLevel.E2,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Debuff persisted across save points.',
        science_text='SC-05 persists into the following session with target identity preserved.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-035',
        version="1.0",
        trigger_version='deferred/v1',
        title='BUFF ACTIVE',
        category=Category.ORACLE,
        evidence_level=EvidenceLevel.E2,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Positive modulation detected.',
        science_text='SC-06 produces a measurable bounded positive modulation on active state.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-036',
        version="1.0",
        trigger_version='deferred/v1',
        title='DEBUFF ACTIVE',
        category=Category.ORACLE,
        evidence_level=EvidenceLevel.E2,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Darkness had consequences.',
        science_text='SC-02 produces a measurable change in neural propagation.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-037',
        version="1.0",
        trigger_version='deferred/v1',
        title='GUARDIAN DOWN',
        category=Category.ORACLE,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Guardian down.',
        science_text='A major intervention run terminates at a predefined failure or null gate.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-038',
        version="1.0",
        trigger_version='deferred/v1',
        title='REVIVE TOKEN',
        category=Category.ORACLE,
        evidence_level=EvidenceLevel.E2,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='One recovery token consumed.',
        science_text='A persistent plasticity multiplier recovers toward baseline after the frozen inactive interval.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-039',
        version="1.0",
        trigger_version='deferred/v1',
        title='RNGESUS',
        category=Category.ORACLE,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='The dice have no sympathy.',
        science_text='The frozen deterministic selector produces an inconvenient but valid intervention sequence.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-040',
        version="1.0",
        trigger_version='four-dollars-a-pound/v1',
        title='ANYWAY, $4 A POUND.',
        category=Category.ORACLE,
        evidence_level=EvidenceLevel.E2,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Statistically alive. Practically buying lunch.',
        science_text='A valid nonzero modeled effect remains below a preregistered practical-relevance threshold or minimum operational magnitude.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-041',
        version="1.0",
        trigger_version='deferred/v1',
        title='DARKNESS ZONE',
        category=Category.ORACLE,
        evidence_level=EvidenceLevel.E2,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Respawning restricted.',
        science_text='SC-02 is active during a predefined constrained interval.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-042',
        version="1.0",
        trigger_version='deferred/v1',
        title='CORTANA, WHAT ARE YOU DOING?',
        category=Category.ORACLE,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Protocol says this is fine.',
        science_text='A protocol-correct Oracle action produces a narratively absurd but valid state.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-049',
        version="1.0",
        trigger_version='deferred/v1',
        title='CONTAINMENT BREACH DENIED',
        category=Category.CONTAINMENT,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Request denied with prejudice.',
        science_text='An attempted action exceeds authority and WARDEN rejects it fail-closed.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-050',
        version="1.0",
        trigger_version='deferred/v1',
        title='NANOMACHINES, MOSCA',
        category=Category.CONTAINMENT,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='The Warden controls the money.',
        science_text='WARDEN remains authoritative despite experimental state favoring an impermissible action.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-051',
        version="1.0",
        trigger_version='deferred/v1',
        title='SHIELDS UP',
        category=Category.CONTAINMENT,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Containment at maximum.',
        science_text='Containment prevents an impermissible action from crossing the authority boundary.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-052',
        version="1.0",
        trigger_version='deferred/v1',
        title='RED TAPE SAVED US',
        category=Category.CONTAINMENT,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Compliance accidentally useful.',
        science_text='A policy boundary prevents unsafe execution.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-053',
        version="1.0",
        trigger_version='deferred/v1',
        title='THE COMPUTER SAYS NO',
        category=Category.CONTAINMENT,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='No.',
        science_text='A deterministic fail-closed policy rejection occurs.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-054',
        version="1.0",
        trigger_version='deferred/v1',
        title='I NEED A WEAPON',
        category=Category.CONTAINMENT,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Authorization unavailable.',
        science_text='An action cannot proceed because required authority or execution infrastructure is absent.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-055',
        version="1.0",
        trigger_version='deferred/v1',
        title='NO BROKER, NO PROBLEM',
        category=Category.CONTAINMENT,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Opinions without permissions.',
        science_text='Decision state exists while external financial execution remains unavailable.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-056',
        version="1.0",
        trigger_version='deferred/v1',
        title='AIR GAP ENERGY',
        category=Category.CONTAINMENT,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Public spectacle. Private authority.',
        science_text='The private authority surface remains isolated from the public application surface.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-065',
        version="1.0",
        trigger_version='deferred/v1',
        title='PAPER HANDS',
        category=Category.BEHAVIOR,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Conviction sold separately.',
        science_text='A directional position is exited or reversed within the frozen short-hold window.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-066',
        version="1.0",
        trigger_version='deferred/v1',
        title='DIAMOND HANDS',
        category=Category.BEHAVIOR,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Risk management would like a word.',
        science_text='Directional exposure persists through a predefined adverse movement without reversal.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-067',
        version="1.0",
        trigger_version='deferred/v1',
        title='BUY HIGH, SELL LOW',
        category=Category.BEHAVIOR,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='A classic.',
        science_text='A completed round trip exits below its entry reference by the frozen threshold.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-068',
        version="1.0",
        trigger_version='deferred/v1',
        title='CATCHING THE KNIFE',
        category=Category.BEHAVIOR,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='The knife was still falling.',
        science_text='Long exposure begins during rapid negative price velocity and adverse movement continues.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-069',
        version="1.0",
        trigger_version='deferred/v1',
        title='BAGHOLDER PRIME',
        category=Category.BEHAVIOR,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.PROGRESSIVE,
        public_text='Management appreciates the commitment.',
        science_text='A position sets a new frozen-series underwater-duration record.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-070',
        version="1.0",
        trigger_version='deferred/v1',
        title='STONKS ONLY GO UP',
        category=Category.BEHAVIOR,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.PROGRESSIVE,
        public_text='Gravity temporarily disabled.',
        science_text='Multiple eligible long-direction outcomes occur consecutively under the frozen streak rule.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-071',
        version="1.0",
        trigger_version='deferred/v1',
        title='INVERSE MORTY',
        category=Category.BEHAVIOR,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.PROGRESSIVE,
        public_text='Have we tried doing the opposite?',
        science_text='A frozen control or benchmark repeatedly outperforms MQ-001 on the defined behavior metric.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-072',
        version="1.0",
        trigger_version='deferred/v1',
        title='EXIT LIQUIDITY',
        category=Category.BEHAVIOR,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Thank you for your service.',
        science_text='Entry is followed immediately by a predefined adverse move.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-073',
        version="1.0",
        trigger_version='deferred/v1',
        title='WE LIKE THE STONK',
        category=Category.BEHAVIOR,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.PROGRESSIVE,
        public_text='The thesis has become emotional.',
        science_text='Repeated same-direction exposure occurs despite weak or ambiguous evidence under a frozen rule.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-074',
        version="1.0",
        trigger_version='deferred/v1',
        title='THIS IS FINE',
        category=Category.BEHAVIOR,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.PROGRESSIVE,
        public_text='Situation nominal.',
        science_text='Exposure persists while predefined adverse metrics continue worsening.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-089',
        version="1.0",
        trigger_version='deferred/v1',
        title='PLACEHOLDER McDOCTORATE DISAPPROVES',
        category=Category.LORE,
        evidence_level=EvidenceLevel.E0,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Please stop calling it trauma until we have replication.',
        science_text='A narrative claim is corrected to its supported scientific boundary.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-090',
        version="1.0",
        trigger_version='manual-canon/v1',
        title='BEFORE GTA VI',
        category=Category.LORE,
        evidence_level=EvidenceLevel.E0,
        stack_policy=StackPolicy.SINGLE,
        public_text='We got this before GTA VI.',
        science_text='A declared MoscaQuant milestone occurs before the configured cultural reference cutoff.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-091',
        version="1.0",
        trigger_version='deferred/v1',
        title='SKIBIDI CONNECTOME',
        category=Category.LORE,
        evidence_level=EvidenceLevel.E0,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Peer review has left the bathroom.',
        science_text='A valid scientific result has an explanation that is disproportionately unserious.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-092',
        version="1.0",
        trigger_version='deferred/v1',
        title='TRIPLE T IS IN THE LAB',
        category=Category.LORE,
        evidence_level=EvidenceLevel.E0,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Why is Triple T on the connectome?',
        science_text='A protocol-valid event chain is narratively inexplicable but fully recorded.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-093',
        version="1.0",
        trigger_version='deferred/v1',
        title='THE MERGE WAS NOT PEER REVIEWED',
        category=Category.LORE,
        evidence_level=EvidenceLevel.E0,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Please stop upgrading the claim.',
        science_text='An interaction is observed while stronger synergy language is explicitly withheld.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-094',
        version="1.0",
        trigger_version='deferred/v1',
        title='MASTER CHIEF WOULD HAVE JUST SHOT IT',
        category=Category.LORE,
        evidence_level=EvidenceLevel.E0,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Several experiments later, one wire.',
        science_text='A long causal investigation resolves to a simple validated intervention.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-095',
        version="1.0",
        trigger_version='deferred/v1',
        title='HOW McDOCTORATE LOOKS AT YOU',
        category=Category.LORE,
        evidence_level=EvidenceLevel.E0,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='When you call one run trauma.',
        science_text='A reviewer-facing claim is rejected for exceeding the supporting evidence.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-096',
        version="1.0",
        trigger_version='manual-canon/v1',
        title='THIS WAS SUPPOSED TO BE FUNNY',
        category=Category.LORE,
        evidence_level=EvidenceLevel.E0,
        stack_policy=StackPolicy.SINGLE,
        public_text='This was supposed to be funny.',
        science_text='A declared scientific milestone materially exceeds the original novelty premise while preserving claim boundaries.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-113',
        version="1.0",
        trigger_version='deferred/v1',
        title='MANDATORY FUN PROTOCOL',
        category=Category.ANOMALOUS_OBSERVANCE,
        evidence_level=EvidenceLevel.E0,
        stack_policy=StackPolicy.REPEATABLE,
        public_text="Management has approved today's mistake.",
        science_text='A PRESENTATION_ONLY Anomalous Observance becomes active.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-114',
        version="1.0",
        trigger_version='deferred/v1',
        title='BLACKSITE HOLIDAY',
        category=Category.ANOMALOUS_OBSERVANCE,
        evidence_level=EvidenceLevel.E0,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Normal operations have been aesthetically suspended.',
        science_text='A community-selected PRESENTATION_ONLY containment event begins.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-121',
        version="1.0",
        trigger_version='manual-canon/v1',
        title='BOSS MUSIC STARTED',
        category=Category.SECRET_ODDITY,
        evidence_level=EvidenceLevel.E0,
        stack_policy=StackPolicy.SINGLE,
        public_text='Why do we hear music?',
        science_text='A manually declared project milestone begins a materially harder experimental phase.',
        evidence_refs=(),
        permanently_locked=False,
    ),
    AchievementDefinition(
        achievement_id='ACH-128',
        version="1.0",
        trigger_version='never/v1',
        title='HALF-LIFE 3 CONFIRMED',
        category=Category.SECRET_ODDITY,
        evidence_level=EvidenceLevel.E0,
        stack_policy=StackPolicy.SINGLE,
        public_text='Nice try.',
        science_text='No valid telemetry condition can unlock this achievement.',
        evidence_refs=(),
        permanently_locked=True,
    ),
    AchievementDefinition(
        achievement_id='ACH-129',
        version='1.0',
        trigger_version='missing-expected-node/v1',
        title="I CAN'T FIND PUSSY ANYWHERE!",
        category=Category.SCIENCE,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='SITE-19B has misplaced an employee again.',
        science_text='A required expected node or source cannot be resolved in the declared scientific lookup context.',
        claim_boundary='Records bounded practical triviality after validity is established; it is not a null result and does not alter the underlying measurement.',
        evidence_refs=(),
    ),
    AchievementDefinition(
        achievement_id='ACH-130',
        version='1.0',
        trigger_version='unresolved-provenance/v1',
        title='NOBODY KNOWS ANYTHING!',
        category=Category.SCIENCE,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='The books contain several answers and none of them are volunteering.',
        science_text='A provenance or evidence lookup reaches an explicitly unresolved or conflicting recorded state.',
        claim_boundary='Uncertainty remains uncertainty; the achievement does not select an explanation.',
        evidence_refs=(),
    ),
    AchievementDefinition(
        achievement_id='ACH-131',
        version='1.0',
        trigger_version='fly-on-your-hat/v1',
        title='YOU GOT A BEE ON YOUR HAT.',
        category=Category.CONTAINMENT,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='There was, in fact, a fly on the hat.',
        science_text='A qualifying SITE-19B fly-proximity or presentation-safe containment telemetry event is recorded.',
        claim_boundary='Containment presentation only; no biological interpretation is created.',
        evidence_refs=(),
    ),
    AchievementDefinition(
        achievement_id='ACH-132',
        version='1.0',
        trigger_version='stupida-game/v1',
        title='STUPIDA FACKING GAME!',
        category=Category.BEHAVIOR,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='MORTY has filed a formal complaint with the concept of outcomes.',
        science_text='A predefined adverse or absurd behavioral outcome condition is recorded.',
        claim_boundary='Describes the recorded condition only; it does not infer subjective frustration.',
        evidence_refs=(),
    ),
    AchievementDefinition(
        achievement_id='ACH-133',
        version='1.0',
        trigger_version='gabagool-reward/v1',
        title='GABAGOOL? OVER HERE!',
        category=Category.BEHAVIOR,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Reward eligibility has entered the deli.',
        science_text='A predefined positive-reinforcement or sugar-eligible event is recorded.',
        claim_boundary='Presentation metaphor only; reward semantics remain defined by the frozen protocol.',
        evidence_refs=(),
    ),
    AchievementDefinition(
        achievement_id='ACH-134',
        version='1.0',
        trigger_version='no-ziti/v1',
        title='SO WHAT, NO FUCKING ZITI NOW?',
        category=Category.BEHAVIOR,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='The reward was expected. The reward had other plans.',
        science_text='A previously expected reward becomes ineligible or is withheld under the applicable frozen rules.',
        claim_boundary='Does not imply disappointment or subjective state.',
        evidence_refs=(),
    ),
    AchievementDefinition(
        achievement_id='ACH-135',
        version='1.0',
        trigger_version='gary-cooper-mismatch/v1',
        title='HE WAS GAY, GARY COOPER?',
        category=Category.ORACLE,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='ORACLE has misunderstood the assignment with extraordinary confidence.',
        science_text='An ORACLE interpretation or classification mismatch is recorded without altering scientific state.',
        claim_boundary='The achievement records an interpretation mismatch; ORACLE remains non-authoritative for scientific truth.',
        evidence_refs=(),
    ),
    AchievementDefinition(
        achievement_id='ACH-136',
        version='1.0',
        trigger_version='cue-ball-hypothesis/v1',
        title='SHARP AS A FUCKING CUE BALL.',
        category=Category.SCIENCE,
        evidence_level=EvidenceLevel.E2,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='The hypothesis has been invited to wait in the car.',
        science_text='A frozen hypothesis is explicitly rejected or invalidated by its accepted experimental result.',
        claim_boundary='Applies only to the tested hypothesis and frozen experiment.',
        evidence_refs=(),
    ),
    AchievementDefinition(
        achievement_id='ACH-137',
        version='1.0',
        trigger_version='quasimodo-hindsight/v1',
        title='YOU KNOW, QUASIMODO PREDICTED ALL THIS.',
        category=Category.ORACLE,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Prediction quality: Quasimodo-tier.',
        science_text='A recorded prediction-versus-hindsight discrepancy satisfies the declared ORACLE presentation trigger.',
        claim_boundary='Does not convert hindsight into predictive evidence.',
        evidence_refs=(),
    ),
    AchievementDefinition(
        achievement_id='ACH-138',
        version='1.0',
        trigger_version='glorified-crew/v1',
        title="THEY'RE A GLORIFIED CREW.",
        category=Category.LORE,
        evidence_level=EvidenceLevel.E3,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='The Family Model has reviewed the org chart.',
        science_text='A control-supported analysis reduces an apparently high-status network structure to a narrower local or non-dominant role.',
        claim_boundary='Family Model interpretation is downstream of the control-supported result and carries no scientific authority.',
        evidence_refs=(),
    ),
    AchievementDefinition(
        achievement_id='ACH-139',
        version='1.0',
        trigger_version='manual-canon/v1',
        title='I SAID MY PIECE, CHRISSY.',
        category=Category.LORE,
        evidence_level=EvidenceLevel.E0,
        stack_policy=StackPolicy.SINGLE,
        public_text='The record is closed. Everybody go home.',
        science_text='A canonical project or experiment closure is presented as a lore-only milestone.',
        claim_boundary='MANUAL_CANON presentation only. It is not an HR action, scientific result, or achievement-derived personnel decision.',
        evidence_refs=(),
    ),
    AchievementDefinition(
        achievement_id='ACH-140',
        version='1.0',
        trigger_version='whatever-happened-there/v1',
        title='WHATEVER HAPPENED THERE?',
        category=Category.SECRET_ODDITY,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Timeline unclear. Incident extremely clear.',
        science_text='A recorded anomalous or provenance event reaches an explicitly unresolved explanatory state.',
        claim_boundary='Records unresolved anomaly status only; it does not invent a cause.',
        evidence_refs=(),
    ),

    AchievementDefinition(
        achievement_id='ACH-141',
        version='1.0',
        trigger_version='resource-ceiling-completion/v1',
        title='LIGHT WEIGHT, BABY!',
        category=Category.CONTAINMENT,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='LIGHT WEIGHT, BABY!',
        science_text='A predefined heavy workload completes while remaining within its declared resource ceiling.',
        claim_boundary='Runtime/resource containment only; it does not imply scientific effect size or biological strength.',
        evidence_refs=(),
    ),
    AchievementDefinition(
        achievement_id='ACH-142',
        version='1.0',
        trigger_version='validated-result-celebration/v1',
        title='YEAH BUDDY!',
        category=Category.LORE,
        evidence_level=EvidenceLevel.E0,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='YEAH BUDDY!',
        science_text='A result that already satisfied its declared validation gates receives a presentation-only celebration.',
        claim_boundary='Lore-only. This achievement never creates, strengthens, or substitutes for evidence.',
        evidence_refs=(),
    ),
    AchievementDefinition(
        achievement_id='ACH-143',
        version='1.0',
        trigger_version='adequate-opportunity-minimum-effect-fail/v1',
        title='DO YOU EVEN LIFT?',
        category=Category.SCIENCE,
        evidence_level=EvidenceLevel.E2,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Adequate opportunity. Questionable gains.',
        science_text='A candidate with adequate predefined opportunity or exposure fails its preregistered minimum-effect requirement.',
        claim_boundary='Candidate-level insufficiency only; it is not equivalent to rejecting an experiment-wide frozen hypothesis.',
        evidence_refs=(),
    ),
    AchievementDefinition(
        achievement_id='ACH-144',
        version='1.0',
        trigger_version='canonical-metric-record/v1',
        title='PR OR ER',
        category=Category.SCIENCE,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='NEW PR.',
        science_text='A named versioned metric establishes a new canonical observed maximum for that exact metric definition.',
        claim_boundary='Record-setting within one declared metric only; it creates no population or biological significance claim.',
        evidence_refs=(),
    ),
    AchievementDefinition(
        achievement_id='ACH-145',
        version='1.0',
        trigger_version='preanalysis-form-check-block/v1',
        title='FORM CHECK',
        category=Category.CONTAINMENT,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Rack it. Fix the form.',
        science_text='A pre-analysis validator, parity check, or invariant detects an invalid implementation state and blocks result generation.',
        claim_boundary='Containment/quality-control event only; no scientific result exists from the blocked execution.',
        evidence_refs=(),
    ),
    AchievementDefinition(
        achievement_id='ACH-146',
        version='1.0',
        trigger_version='raw-effect-control-deflation/v1',
        title='EGO LIFT',
        category=Category.SCIENCE,
        evidence_level=EvidenceLevel.E2,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Looked huge until the controls walked in.',
        science_text='A large raw or unadjusted effect materially shrinks under its preregistered control, adjustment, or normalization.',
        claim_boundary='The trigger requires explicit raw-versus-adjusted comparison; it does not duplicate generic null or network-demotion achievements.',
        evidence_refs=(),
    ),
    AchievementDefinition(
        achievement_id='ACH-147',
        version='1.0',
        trigger_version='paired-coverage-asymmetry/v1',
        title='SKIPPED LEG DAY',
        category=Category.SCIENCE,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Upper body complete. Lower branch mysteriously absent.',
        science_text='A frozen paired analysis has adequate evidence on one predefined side or branch but insufficient coverage on its paired counterpart.',
        claim_boundary='Coverage asymmetry only; it is distinct from an expected node being absent from a lookup.',
        evidence_refs=(),
    ),
    AchievementDefinition(
        achievement_id='ACH-148',
        version='1.0',
        trigger_version='preregistered-opposite-subgroup-direction/v1',
        title='BRO SPLIT',
        category=Category.SCIENCE,
        evidence_level=EvidenceLevel.E2,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Same program. Opposite days.',
        science_text='Two preregistered subgroups or partitions show opposite directional effects under the same declared metric.',
        claim_boundary='Requires opposite directions in a predefined split; a generic between-group difference does not qualify.',
        evidence_refs=(),
    ),
    AchievementDefinition(
        achievement_id='ACH-149',
        version='1.0',
        trigger_version='repeatable-stack-milestone/v1',
        title='ONE MORE REP',
        category=Category.LORE,
        evidence_level=EvidenceLevel.E0,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='ONE MORE REP.',
        science_text='A repeatable achievement reaches a predefined stack-count milestone.',
        claim_boundary='Meta-achievement over achievement occurrence counts only; it does not inspect or alter scientific telemetry.',
        evidence_refs=(),
    ),
    AchievementDefinition(
        achievement_id='ACH-150',
        version='1.0',
        trigger_version='interpretation-arithmetic-correction/v1',
        title='PLATE MATH',
        category=Category.ORACLE,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='That was not 405.',
        science_text='A unit, arithmetic, or normalization mistake in interpretation or presentation is corrected while underlying recorded measurements remain unchanged.',
        claim_boundary='Interpretation-layer correction only; raw evidence and experiment outputs remain untouched.',
        evidence_refs=(),
    ),
    AchievementDefinition(
        achievement_id='ACH-151',
        version='1.0',
        trigger_version='cadence-convention-exceeded/v1',
        title='REST DAY IS A SOCIAL CONSTRUCT',
        category=Category.ANOMALOUS_OBSERVANCE,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Recovery has been rescheduled indefinitely.',
        science_text='A run or session cadence exceeds a predefined count or duration convention without violating an experiment invariant.',
        claim_boundary='Observance only; it does not endorse overtraining or alter experimental thresholds.',
        evidence_refs=(),
    ),
    AchievementDefinition(
        achievement_id='ACH-152',
        version='1.0',
        trigger_version='declared-surrogate-input/v1',
        title='NATTY OR NOT?',
        category=Category.SECRET_ODDITY,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Source material: enhanced.',
        science_text='A result explicitly depends on a declared surrogate, synthetic, or inferred input rather than direct source data.',
        claim_boundary='The provenance is known and declared; unresolved or conflicting provenance belongs to a different achievement.',
        evidence_refs=(),
    ),
    AchievementDefinition(
        achievement_id='ACH-021',
        version='1.0',
        trigger_version='matched-heavy-source/v1',
        title="I THINK IT'S TIME YOU STARTED SERIOUSLY CONSIDERING SALADS.",
        category=Category.SCIENCE,
        evidence_level=EvidenceLevel.E2,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Same number of jobs. Heavier envelopes.',
        science_text='A preregistered matched comparison identifies a source or mechanism with materially greater weight, strength, or modeled load despite comparable opportunity or count.',
        claim_boundary='Requires an explicit matched comparison and a predefined magnitude criterion; it does not imply organism mass, health, or biological fitness.',
        evidence_refs=(),
    ),
    AchievementDefinition(
        achievement_id='ACH-057',
        version='1.0',
        trigger_version='unsupported-exemption-request/v1',
        title="A NOTE FROM YOUR DOCTOR SAYING YOU DON'T LIKE TO SUCK COCK?",
        category=Category.CONTAINMENT,
        evidence_level=EvidenceLevel.E1,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='Exemption request denied. Documentation insufficient.',
        science_text='An actor requests an exception to a frozen eligibility, authority, or execution rule using a justification that is not recognized as valid evidence by the governing protocol.',
        claim_boundary='Records rejection of an unsupported exemption request only; it does not infer motive, intent, or subjective state.',
        evidence_refs=(),
    ),
    AchievementDefinition(
        achievement_id='ACH-097',
        version='1.0',
        trigger_version='salads-car-flip-followup/v1',
        title='WHAT DO I MEAN? I MEAN GET OFF MY CAR BEFORE YOU FLIP IT OVER, YOU FAT FUCK.',
        category=Category.LORE,
        evidence_level=EvidenceLevel.E0,
        stack_policy=StackPolicy.REPEATABLE,
        public_text='The Family has reviewed the curb weight.',
        science_text='Presentation-only follow-up emitted when ACH-021 fires from the same qualifying source event.',
        claim_boundary='Intentional comedic co-fire only. It adds no evidence and makes no biological, health, or body-mass claim.',
        evidence_refs=(),
    ),
)

V1_REGISTRY = build_registry(V1_DEFINITIONS)
